// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlsfppeaokwwyyzxvkaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsc2ZwcGVhb2t3d3l5enh2a2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjAzOTIsImV4cCI6MjA2MDAzNjM5Mn0.uReJTtIZQkId3gNHsNGucHvaLxX1jRRq9vge-ulFFLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);